name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Publish Blog with Papertown
        uses: ChristianKohler/papertown-github-action@v1.0.1
        with: 
          devto-api-key: ${{ secrets.DEVTO_API_KEY }}
